/** @type {import("tailwindcss").Config} */
module.exports = {
  theme: {
    extend: {
      typography: () => ({
        mikado: {
          css: {
            "code::before": { content: "none" },
            "code::after": { content: "none" },
            "--tw-prose-body": "var(--color-mikado-800)",
            "--tw-prose-headings": "var(--color-mikado-900)",
            "--tw-prose-lead": "var(--color-mikado-700)",
            "--tw-prose-links": "var(--color-mikado-900)",
            "--tw-prose-bold": "var(--color-mikado-900)",
            "--tw-prose-counters": "var(--color-mikado-600)",
            "--tw-prose-bullets": "var(--color-mikado-400)",
            "--tw-prose-hr": "var(--color-mikado-300)",
            "--tw-prose-quotes": "var(--color-mikado-900)",
            "--tw-prose-quote-borders": "var(--color-mikado-300)",
            "--tw-prose-captions": "var(--color-mikado-700)",
            "--tw-prose-code": "var(--color-mikado-900)",
            "--tw-prose-pre-code": "var(--color-mikado-100)",
            "--tw-prose-pre-bg": "var(--color-mikado-900)",
            "--tw-prose-th-borders": "var(--color-mikado-300)",
            "--tw-prose-td-borders": "var(--color-mikado-200)",
            "--tw-prose-invert-body": "var(--color-mikado-50)",
            "--tw-prose-invert-headings": "var(--color-mikado-50)",
            "--tw-prose-invert-lead": "var(--color-mikado-50)",
            "--tw-prose-invert-links": "var(--color-white)",
            "--tw-prose-invert-bold": "var(--color-mikado-50)",
            "--tw-prose-invert-counters": "var(--color-mikado-500)",
            "--tw-prose-invert-bullets": "var(--color-mikado-500)",
            "--tw-prose-invert-hr": "var(--color-mikado-500)",
            "--tw-prose-invert-quotes": "var(--color-mikado-200)",
            "--tw-prose-invert-quote-borders": "var(--color-mikado-500)",
            "--tw-prose-invert-captions": "var(--color-mikado-200)",
            "--tw-prose-invert-code": "var(--color-white)",
            "--tw-prose-invert-pre-code": "var(--color-mikado-50)",
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": "var(--color-mikado-600)",
            "--tw-prose-invert-td-borders": "var(--color-mikado-500)",
          },
        },
      }),
    },
  },
};
